/*
 * generated by Xtext 2.32.0
 */
package org.example.games.generator

import org.example.games.games.*

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 * «game.name.toFirstUpper»
 */
class GamesGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		val model = resource.contents.head as Model

		for (game : model.elements.filter(Game)) {
			fsa.generateFile(
				game.name.toFirstUpper + "Game" + ".java",
				game.compile()
			)
		}

		// no leading '/' – generate into src-gen/GameEngine/Player.java
		fsa.generateFile("GameEngine/Player.java", playerClass)
	}

	def CharSequence compile(Game game) {
		'''
				
			import java.util.Map;
			import java.util.HashMap;
			import GameEngine.*;
				
			public class «game.name.toFirstUpper»Game {
				
				  
			«FOR v : (game.eContainer as Model).elements.filter(IntVar)»
				«v.extendIntVar»
			«ENDFOR»
					
			 
			«FOR c : (game.eContainer as Model).elements.filter(Condition)»
				«c.extendCondition(game)»
			«ENDFOR»
			«game.rule.extendRule(game)»
					 
					   
			«FOR d : (game.eContainer as Model).elements.filter(Decision)»
				«d.extendDecision(game)»
			«ENDFOR»
					 
			  
			«game.script.extendScript(game)»
			
			«FOR p : (game.eContainer as Model).elements.filter(Player)»
				«p.extendPlayer»
			«ENDFOR»
							
			public static void main(String[] args) {
			  «game.name.toFirstUpper»Game g = new «game.name.toFirstUpper»Game();
			  g.runScript(g.«game.player1.name», g.«game.player2.name»);
			}
			}
		'''
	}

	def extendIntVar(IntVar I) {
		'''
			public static final «I.type.name» «I.name» = «I.init.extendExpression»;
		'''
	}

	def extendScript(Script script, Game game) {
		'''
			public void runScript(
			    Player«game.player1.name» «game.player1.name»,
			    Player«game.player2.name» «game.player2.name») {
			«FOR t : script.turns»
				«t.extendTurns»
			«ENDFOR»
			}
		'''
	}

	def extendTurns(Turns turns) {
		'''
			System.out.println("Turn: «turns.index»");
			System.out.println("Player Name: «turns.player.name»");
			«turns.decision.name».«turns.decision.name»_func(
			    «turns.decision.me.name», «turns.decision.other.name»);
		'''
	}

	def CharSequence extendRule(Rule rule, Game g) {
		'''
			boolean winCond()  { return «rule.winCondition.name»(«g.player1.name»,«g.player2.name»); }
			boolean loseCond() { return «rule.loseCondition.name»(«g.player1.name»,«g.player2.name»); }
		'''
	}

	def CharSequence extendCondition(Condition cond, Game g) {
		'''
			boolean «cond.name»(Player«g.player1.name» «g.player1.name», Player«g.player2.name» «g.player2.name») {
			  return «cond.boolexp.extendExpression»;
			}
		'''
	}

	def CharSequence extendDecision(Decision decision, Game g) {
		'''
			static class «decision.name» {
			  public static void «decision.name»_func(
			      Player«decision.me.name» «decision.me.name»,
			      Player«decision.other.name» «decision.other.name») {
			
			    «decision.body.extendBlock»
			    if(this.winCond()){
			    	System.out.println("«g.player1.name» has Won !!!";
			    	System.out.println("«g.player2.name» has Lost !!!";
			    }
			    if(this.loseCond()){
			    	System.out.println("«g.player2.name» has Won !!!";
			    	System.out.println("«g.player1.name» has Lost !!!";
			    }
			  }
			}
		'''
	}

	def extendBlock(Block block) {
		'''
			«FOR s : block.statements»
				«s.extendStatement»
			«ENDFOR»
		'''
	}

	def CharSequence playerClass() {
		'''
			package GameEngine;
			import java.util.Map;
			import java.util.HashMap;
			
			public class Player{
				public int health;
				public Map<String, Integer> resources = new HashMap<>();
				public Map<String, Integer> military  = new HashMap<>();
				public Map<String, Integer> IntVars  = new HashMap<>();
				
				public void addIntVar(String key,int value){
					this.IntVars.put(key,value);
				}
				
				public void setHealth(int health){
					this.health = health;
				}
			
				public int getHealth(){
					return this.health;
				}
				
				public void setResource(String key, int value){
					this.resources.put(key,value);
				}
				
				public void setMilitary(String key, int value){
					this.military.put(key,value);	
				}
			}
		'''
	}

	def CharSequence extendPlayer(Player pl) {
		'''
			class Player«pl.name» extends Player {
			  // player‑specific integer variables (e.g. baseDamage, agility, stamina,…)
			  «FOR i : pl.vars»
			  	public «i.type.name» «i.name» = «i.init.extendExpression»;
			  «ENDFOR»
			
			  public Player«pl.name»() {
			  this.health = «pl.health»;
			  «FOR r : pl.resources»
			  	this.resources.put("«r.name»", «r.init.extendExpression»);
			  «ENDFOR»
			  «FOR m : pl.militaryResources»
			  	this.military.put("«m.name»", «m.init.extendExpression»);
			  «ENDFOR»
			  }
			}
			
			public Player«pl.name» «pl.name» = new Player«pl.name»();
		'''
	}

	def dispatch extendStatement(Conditional cond) {
		'''
			if(«cond.condition.extendExpression»){
				«cond.thenBlock.extendBlock»
			}  
			«FOR i : 0 ..< cond.elifBlocks.size»
				else if («cond.elifConditions.get(i).extendExpression»)
				{
					«cond.elifBlocks.get(i).extendBlock»
				} 
			«ENDFOR»
			«IF cond.elseBlock !== null»
				else {
					«cond.elseBlock.extendBlock»
				}
			«ENDIF»
		'''
	}

	def dispatch extendStatement(ExpressionStmt exp) {
		'''
			«exp.expr.extendExpression»
		'''
	}

	def dispatch extendStatement(IntVar i) {
		'''
			«i.extendIntVar»
		'''

	}

	def dispatch extendStatement(PrintStmt p) {
		'''
			System.out.println("«p.value»");
		'''
	}

	def dispatch extendStatement(Assignment A) {
		// Special-case assignments to player.health -> call setter instead of direct field assign
		if ((A.target instanceof PlayerVarLValue && (A.target as PlayerVarLValue).varName == 'health') ||
			(A.target instanceof PlayerHealthLValue)) {
			val playerName = if(A.target instanceof PlayerVarLValue) (A.target as PlayerVarLValue).player.name else (A.
					target as PlayerHealthLValue).player.name
			'''«playerName».setHealth(«A.expression.extendExpression»);'''
		} else {
			'''
				«A.target.extendLVal» = «A.expression.extendExpression»;
			'''
		}
	}

	def dispatch extendLVal(PlayerVarLValue plVal) {
		if (plVal.varName == 'health') {
			// prefer the getter for health to be robust against future visibility changes
			'''«plVal.player.name».getHealth()'''
		} else {
			'''«plVal.player.name».«plVal.varName» '''
		}
	}

	def dispatch extendLVal(PlayerHealthLValue phVal) {
		// explicit handler for the PlayerHealthLValue type introduced in the grammar
		'''«phVal.player.name».getHealth()'''
	}

	def dispatch extendLVal(VarLValue rVal) {
		'''«rVal.varName» '''
	}

	def dispatch extendExpression(Expression exp) {
		'''
			/* Unknown Expression Type */
		'''
	}

	def dispatch extendExpression(OrExpression orExp) {
		'''(«orExp.left.extendExpression» || «orExp.right.extendExpression»)'''
	}

	def dispatch extendExpression(AndExpression andExp) {
		'''(«andExp.left.extendExpression» && «andExp.right.extendExpression»)'''
	}

	def dispatch extendExpression(Comparison cmpExp) {
		'''(«cmpExp.left.extendExpression» «cmpExp.op» «cmpExp.right.extendExpression»)'''
	}

	def dispatch extendExpression(Plus pl) {
		'''(«pl.left.extendExpression» + «pl.right.extendExpression»)'''
	}

	def dispatch extendExpression(Minus mn) {
		'''(«mn.left.extendExpression» - «mn.right.extendExpression»)'''
	}

	def dispatch extendExpression(Mult ml) {
		'''(«ml.left.extendExpression» * «ml.right.extendExpression»)'''
	}

	def dispatch extendExpression(Div div) {
		'''(«div.left.extendExpression»/«div.right.extendExpression»)'''
	}

	def dispatch extendExpression(IntConstant IC) {
		'''(«IC.value»)'''
	}

	def dispatch extendExpression(BoolConstant Bl) {
		'''«Bl.value»'''
	}

	def dispatch extendExpression(Not nt) {
		'''!«nt.expression.extendExpression»'''
	}

	def dispatch extendExpression(LValueExpr LVE) {
		'''«LVE.target.extendLVal»'''
	}

}
