/*
 * generated by Xtext 2.32.0
 */
package org.example.games.generator

import org.example.games.games.*

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 * «game.name.toFirstUpper»
 */
class GamesGenerator extends AbstractGenerator {

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
//		fsa.generateFile('greetings.txt', 'People to greet: ' + 
//			resource.allContents
//				.filter(Greeting)
//				.map[name]
//				.join(', '))
		val model = resource.contents.head as Model

		val playerArr = newArrayList

		for (game : model.elements.filter(Game)) {
			fsa.generateFile(
				game.name.toFirstUpper + ".java",
				game.compile()
			)
		}
	}

	def CharSequence compile(Game game) {
		'''
		package my.generated;
		
		import java.util.Map;
		import java.util.HashMap;
		
		public class «game.name.toFirstUpper»Game {
		
		  
		  «FOR v : (game.eContainer as Model).elements.filter(IntVar)»
		  	«v.extendIntVar»
		  «ENDFOR»
		
		  
		  «FOR p : (game.eContainer as Model).elements.filter(Player)»
			«p.extendPlayer»
			«ENDFOR»
			
			 
			  «game.setup.extendSetup»
			
			 
			  «FOR c : (game.eContainer as Model).elements.filter(Condition)»
				«c.extendCondition»
				«ENDFOR»
				«game.rule.extendRule»
				
				  
				  «FOR d : (game.eContainer as Model).elements.filter(Decision)»
					«d.extendDecision»
					«ENDFOR»
					
					  
					  «game.script.extendScript»
					
					  public static void main(String[] args) {
					  «game.name.toFirstUpper»Game g = new «game.name.toFirstUpper»Game();
					  g.runScript();
					  }
					}
		'''
	}

	def extendIntVar(IntVar I) {
		'''
		public «I.type.name» «I.name» = «I.init.extendExpression»;
		'''
	}

	def CharSequence extendSetup(Setup st) {
		'''
		public int timelimit = «IF st.limitName !== null»«st.limitName»«ELSE»0«ENDIF»;
		

		public Player«st.player1.name» player1 = «st.player1.name»;
		public Player«st.player2.name» player2 = «st.player2.name»;
		'''
	}

	def extendScript(Script script) {
		'''
		«FOR t : script.turns»
			«t.extendTurns»
		«ENDFOR»
		'''
	}

	def extendTurns(Turns turns) {
		'''
		System.out.println("Turn: «turns.index»");
		System.out.println("Player Name: «turns.player.name»");
		«turns.decision.name».«turns.decision.name»_func(«turns.decision.me»,«turns.decision.other»);
		'''
	}

	def CharSequence extendRule(Rule rule) {
		'''
		boolean winCond()  { return «rule.winCondition.name»(); }
		boolean loseCond() { return «rule.loseCondition.name»(); }
		'''
	}

	def CharSequence extendCondition(Condition cond) {
		'''
		boolean «cond.name»() {
		  return «cond.boolexp.extendExpression»;
		}
		'''
	}

	def CharSequence extendDecision(Decision decision) {
		'''
		static class «decision.name» {
		  public static void «decision.name»_func(
		      Player«decision.me.name» me,
		      Player«decision.other.name» other) {
		
		    «decision.body.extendBlock»
		  }
		}
		'''
	}

	def extendBlock(Block block) {
		'''
		«FOR s : block.statements»
			«s.extendStatement»
		«ENDFOR»
		'''
	}

	def CharSequence extendPlayer(Player pl) {
		'''
		class Player«pl.name» {
		  «FOR i : pl.vars»
		  	«i.extendIntVar»
		  «ENDFOR»
		
		  public int health = «pl.health»;
		  private Map<String, Integer> resources = new HashMap<>();
		  private Map<String, Integer> military  = new HashMap<>();
		
		  public Player«pl.name»() {
		  «FOR r : pl.resources»
		  	resources.put("«r.name»", «r.init.extendExpression»);
		  «ENDFOR»
		  «FOR m : pl.militaryResources»
		  	military.put("«m.name»", «m.init.extendExpression»);
		  «ENDFOR»
		  }
		}
		
		public Player«pl.name» «pl.name» = new Player«pl.name»();
		'''
	}

	def dispatch extendStatement(Conditional cond) {
		'''
		if(«cond.condition.extendExpression»){
			«cond.thenBlock.extendBlock»
		}  
		«FOR i : 0 ..< cond.elifBlocks.size»
			else if («cond.elifConditions.get(i).extendExpression»)
			{
				«cond.elifBlocks.get(i).extendBlock»
			} 
		«ENDFOR»
		«IF cond.elseBlock !== null»
			else {
				«cond.elseBlock.extendBlock»
			}
		«ENDIF»
		'''
	}

	def dispatch extendStatement(ExpressionStmt exp) {
		'''
		«exp.expr.extendExpression»
		'''
	}

	def dispatch extendStatement(IntVar i) {
		'''
		«i.extendIntVar»
		'''

	}

	def dispatch extendStatement(PrintStmt p) {
		'''
		System.out.println("«p.value»");
		'''
	}

	def dispatch extendStatement(Assignment A) {
		'''
		«A.target.extendLVal» «A.expression.extendExpression»;
		'''
	}

	def dispatch extendLVal(PlayerVarLValue plVal) {
		'''«plVal.player.name».«plVal.varName» = '''
	}

	def dispatch extendLVal(VarLValue rVal) {
		'''«rVal.varName» = '''
	}

	def dispatch extendExpression(Expression exp) {
		'''
			/* Unknown Expression Type */
		'''
	}

	def dispatch extendExpression(OrExpression orExp) {
		'''(«orExp.left.extendExpression» || «orExp.right.extendExpression»)'''
	}

	def dispatch extendExpression(AndExpression andExp) {
		'''(«andExp.left.extendExpression» && «andExp.right.extendExpression»)'''
	}

	def dispatch extendExpression(Comparison cmpExp) {
		'''(«cmpExp.left.extendExpression» «cmpExp.op» «cmpExp.right.extendExpression»)'''
	}

	def dispatch extendExpression(Plus pl) {
		'''(«pl.left.extendExpression» + «pl.right.extendExpression»)'''
	}

	def dispatch extendExpression(Minus mn) {
		'''(«mn.left.extendExpression» - «mn.right.extendExpression»)'''
	}

	def dispatch extendExpression(Mult ml) {
		'''(«ml.left.extendExpression» * «ml.right.extendExpression»)'''
	}

	def dispatch extendExpression(Div div) {
		'''(«div.left.extendExpression»/«div.right.extendExpression»)'''
	}

	def dispatch extendExpression(IntConstant IC) {
		'''(«IC.value»)'''
	}

	def dispatch extendExpression(BoolConstant Bl) {
		'''«Bl.value»'''
	}

	def dispatch extendExpression(Not nt) {
		'''!«nt.expression.extendExpression»'''
	}

	def dispatch extendExpression(LValueExpr LVE) {
		'''«LVE.target.extendLVal»'''
	}

}
